### ISSUE TITLE
Support inline code highlighting

### ISSUE THREAD

**Issue by ivan-kleshnin** [ben-eb/remark-highlight.js#26]
Markdown does not define a syntax for language-specific inline code.

But is it possible to handle this (maybe optionally):

* `<code class="css">{color: red;}</code>` 
* `<code class="js">console.log("!!!")</code>`

**Comment by wooorm** [comment]
Hi @ivan-kleshnin! Sorry this went unanswered for a while!

I think that’s a pretty good idea, but I feel it’s better suited as a standalone plugin. Maybe even for [rehype](https://github.com/wooorm/rehype) itself? Feel free to chat about that on [Gitter](https://gitter.im/wooorm/rehype), if you’re interested in building it!

Cheers,
Titus

**Comment by ivan-kleshnin** [comment]
Hi, Titus. No problem. I plan to invest some time in **rehype** ecosystem in the future because of my main project (which is heavily markdown-based). You've made a lot of interesting thematic libraries – I should admit... So I'll definitely consider to create this plugin.

Cheers!

**Comment by wooorm** [comment]
Thanks for the kind words! I hope you’ll try it out, let me know if I can help!

**Comment by babakfp** [comment]
Hi

I was looking to impement the same feature so I wrote this:
https://github.com/babakfp/remark-inline-code-language

But, it seems like I should've made the plugin for rehype because I don't get back the `lang` property in this example:

```
import { unified } from "unified"
import { visit } from "unist-util-visit"
import remarkParse from "remark-parse"
import remarkInlineCodeLanguage from "../../remark-inline-code-language/dist/index.js"
import remarkRehype from "remark-rehype"
import rehypeStringify from "rehype-stringify"

const file = await unified()
	.use(remarkParse)
	.use(remarkInlineCodeLanguage)
	.use(remarkRehype)
	.use(() => {
		return (tree, file) => {
				visit(tree, "element", function visitor(node) {
				console.log(JSON.stringify(node, null, 4))
			})
		}
	})
	.use(rehypeStringify)
	.process("`_js console.log()`")
```

Is that correct? Do I need to build it for rehype or what can I do?

Thanks

**Comment by ChristianMurphy** [comment]
Welcome @babakfp!
That is not what this thread is about, it is about a different, plain HTML syntax.
This tread is also over 6 years old, the project has changed and evolved over the years.
I'd recommend opening a thread in discussions (https://github.com/orgs/remarkjs/discussions) and offering a bit more context on your goal.

The original suggestion that rehype would likely be involve may still holds true https://github.com/remarkjs/remark-highlight.js/issues/26#issuecomment-309117682
But more context can help clarify.

I'm going to lock this thread as it's outdated, and this new conversation is unrelated to the original thread.
But happy to continue the conversation in discussions (https://github.com/orgs/remarkjs/discussions)
