### ISSUE TITLE
Seems not works properly

### ISSUE THREAD

**Issue by greybax** [ben-eb/remark-highlight.js#6]
I'm using it in my [md-content](https://github.com/greybax/md-content) moduleand seems its not worked properly. It's just setted up classes but don't add ```highlight.js``` and styles to the page, so code between these tags is not highlighted.

**Comment by ben-eb** [comment]
Indeed, you have to provide the styles yourself, by loading one of the CSS themes. Loading highlight.js isn't necessary. :smile:

**Comment by greybax** [comment]
Awesome! :) Thank you
